// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLi-G_l3e7P6jewGb5vrRzq8F0CHyWts',
    appId: '1:942555561770:web:6d0f707b9e3f49d8cd2853',
    messagingSenderId: '942555561770',
    projectId: 'expense-tracker-7390f',
    authDomain: 'expense-tracker-7390f.firebaseapp.com',
    storageBucket: 'expense-tracker-7390f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-2eHnU2cASKXo8uZcnpxVRwGAT_Vh4pk',
    appId: '1:942555561770:android:b84136e728dbd6b8cd2853',
    messagingSenderId: '942555561770',
    projectId: 'expense-tracker-7390f',
    storageBucket: 'expense-tracker-7390f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJSQ9OG03AkvRX-2OaC5bm5j1QioLo6E',
    appId: '1:942555561770:ios:a96882728c2bb65acd2853',
    messagingSenderId: '942555561770',
    projectId: 'expense-tracker-7390f',
    storageBucket: 'expense-tracker-7390f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
